# Generated by Django 5.0 on 2024-01-17 04:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCliente', models.CharField(max_length=100)),
                ('apellidoCliente', models.CharField(max_length=100)),
                ('emailCliente', models.EmailField(blank=True, max_length=100, null=True)),
                ('direccionCliente', models.CharField(blank=True, max_length=100, null=True)),
                ('edadCliente', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EspecialidadDoctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidadDoctor', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TipoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoCliente', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreDoctor', models.CharField(max_length=100)),
                ('apellidoDoctor', models.CharField(max_length=100)),
                ('emailDoctor', models.EmailField(blank=True, max_length=100, null=True)),
                ('direccionDoctor', models.CharField(blank=True, max_length=100, null=True)),
                ('edadDoctor', models.IntegerField(blank=True, null=True)),
                ('especialidadDoctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.especialidaddoctor')),
            ],
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreMascota', models.CharField(max_length=100)),
                ('razaMascota', models.CharField(max_length=100)),
                ('descripcionMascota', models.CharField(blank=True, max_length=100, null=True)),
                ('fechanacimientoMascota', models.DateField()),
                ('nombreDoctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.doctor')),
                ('nombreDueno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreConsulta', models.CharField(max_length=100)),
                ('descipcionConsulta', models.CharField(max_length=100)),
                ('fechaConsulta', models.DateField()),
                ('duenoConsulta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.cliente')),
                ('doctorConsulta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.doctor')),
                ('mascotaConsulta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.mascota')),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='tipoCliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.tipocliente'),
        ),
    ]
