# Generated by Django 5.0 on 2024-01-17 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mascota',
            name='nombreDoctor',
        ),
    ]
