# Generated by Django 5.0.1 on 2024-01-16 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='fechaVencimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
